// This file will be auto-generated by GitHub Actions
// Do not edit manually

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      invitation_responses: {
        Row: {
          id: number;
          name: string;
          email: string;
          attendance: "attending" | "not_attending";
          guest_count: number;
          dietary_restrictions: string | null;
          message: string | null;
          created_at: string;
        };
        Insert: {
          id?: number;
          name: string;
          email: string;
          attendance: "attending" | "not_attending";
          guest_count?: number;
          dietary_restrictions?: string | null;
          message?: string | null;
          created_at?: string;
        };
        Update: {
          id?: number;
          name?: string;
          email?: string;
          attendance?: "attending" | "not_attending";
          guest_count?: number;
          dietary_restrictions?: string | null;
          message?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};
